services:
    app:
        container_name: world-countries-app
        build:
            context: .
            dockerfile: ./Dockerfile
        volumes:
            - ./app:/var/www/html
        depends_on:
            - db
        environment:
            XDEBUG_MODE: debug
            XDEBUG_CONFIG: "client_host=host.docker.internal client_port=9003"
    db:
        container_name: world-countries-db
        image: mysql:8.0
        ports:
            - "3307:3306"
        environment:
            MYSQL_ROOT_HOST: '%'
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: world_countries_db
        volumes:
            - ./mysql:/var/lib/mysql
    nginx:
        container_name: world-countries-server
        image: nginx:latest
        ports:
            - "8080:80"
        volumes:
            - ./nginx/conf.d/:/etc/nginx/conf.d
            - ./app:/var/www/htmln
        depends_on:
            - app
